// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DersYuku, otomatik ders programı oluşturmak için kullanılacak olan ders atamalarıdır.
 */
export interface DersYuku {
    "id": number;
    "dersAdi": string;
    "subeId": number;

    /**
     * Kaç saat
     */
    "duration": number;
}

/**
 * HocaDers, bir öğretmenin verebileceği dersleri tanımlar.
 */
export interface HocaDers {
    "id": number;
    "hocaId": number;
    "dersAdi": string;
}

/**
 * ProgramOturumu, takvimde planlanmış olan tek bir oturum bloğudur.
 */
export interface ProgramOturumu {
    "id": number;
    "dersAdi": string;
    "hocaId": number;
    "subeId": number;
    "zoomId": number;
    "turId": number;

    /**
     * 0..39
     */
    "startSlot": number;

    /**
     * Kaç saat süreceği
     */
    "duration": number;
}
