// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VeriService, veri giriş ekranlarının kullandığı basit bir depodur.
 * Yağmur'un formları buna YAZAR (Ekle/Sil), takvim ekranı buradan OKUR (Listele).
 * 
 * Şimdilik veriyi BELLEKTE tutuyoruz: uygulama kapanınca kayıtlar silinir.
 * Kalıcı kayıt (dosya veya SQLite) yol haritasında Aşama 4'te eklenecek.
 * 
 * Not (mutex): Wails metotları farklı goroutine'lerden çağrılabildiği için,
 * listeleri değiştiren/okuyan yerleri bir kilitle koruyoruz. Kilit, aynı anda
 * iki işlemin listeyi bozmasını engeller.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";

export function HocaEkle(ad: string): $CancellablePromise<domain$0.Hoca> {
    return $Call.ByID(3089288467, ad);
}

export function HocaListele(): $CancellablePromise<domain$0.Hoca[] | null> {
    return $Call.ByID(3945048008);
}

export function HocaSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(4250482912, id);
}

export function SubeEkle(ad: string): $CancellablePromise<domain$0.Sube> {
    return $Call.ByID(2399803115, ad);
}

export function SubeListele(): $CancellablePromise<domain$0.Sube[] | null> {
    return $Call.ByID(2887128800);
}

export function SubeSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(1696262536, id);
}

export function ToplantiTuruEkle(ad: string): $CancellablePromise<domain$0.ToplantiTuru> {
    return $Call.ByID(752381417, ad);
}

export function ToplantiTuruListele(): $CancellablePromise<domain$0.ToplantiTuru[] | null> {
    return $Call.ByID(2034350802);
}

export function ToplantiTuruSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(3878888994, id);
}

export function ZoomEkle(ad: string, adres: string): $CancellablePromise<domain$0.Zoom> {
    return $Call.ByID(2856330457, ad, adres);
}

export function ZoomListele(): $CancellablePromise<domain$0.Zoom[] | null> {
    return $Call.ByID(2482967010);
}

export function ZoomSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(682508370, id);
}
