// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DersEkle(ad: string): $CancellablePromise<domain$0.Ders> {
    return $Call.ByID(2654092382, ad);
}

export function DersListele(): $CancellablePromise<domain$0.Ders[] | null> {
    return $Call.ByID(185808055);
}

export function DersSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(494347215, id);
}

export function DersYukuEkle(dersAdi: string, subeID: number, duration: number): $CancellablePromise<$models.DersYuku> {
    return $Call.ByID(3554419428, dersAdi, subeID, duration);
}

export function DersYukuGuncelle(id: number, dersAdi: string, subeID: number, duration: number): $CancellablePromise<void> {
    return $Call.ByID(3624298022, id, dersAdi, subeID, duration);
}

export function DersYukuListele(): $CancellablePromise<$models.DersYuku[] | null> {
    return $Call.ByID(2410627841);
}

export function DersYukuSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(1108198689, id);
}

export function HocaDersEkle(hocaID: number, dersAdi: string): $CancellablePromise<$models.HocaDers> {
    return $Call.ByID(475731067, hocaID, dersAdi);
}

export function HocaDersListele(): $CancellablePromise<$models.HocaDers[] | null> {
    return $Call.ByID(1911795984);
}

export function HocaDersSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(4006142552, id);
}

export function HocaEkle(ad: string): $CancellablePromise<domain$0.Hoca> {
    return $Call.ByID(3089288467, ad);
}

export function HocaListele(): $CancellablePromise<domain$0.Hoca[] | null> {
    return $Call.ByID(3945048008);
}

export function HocaSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(4250482912, id);
}

/**
 * OtomatikOlustur clears current sessions and generates a new schedule based on DersYukleri using a CSP Solver.
 */
export function OtomatikOlustur(): $CancellablePromise<void> {
    return $Call.ByID(2400687683);
}

export function ProgramOturumEkle(dersAdi: string, hocaID: number, subeID: number, zoomID: number, turID: number, startSlot: number, duration: number): $CancellablePromise<$models.ProgramOturumu> {
    return $Call.ByID(2358723398, dersAdi, hocaID, subeID, zoomID, turID, startSlot, duration);
}

export function ProgramOturumGuncelle(id: number, dersAdi: string, hocaID: number, subeID: number, zoomID: number, turID: number, startSlot: number, duration: number): $CancellablePromise<void> {
    return $Call.ByID(3181058000, id, dersAdi, hocaID, subeID, zoomID, turID, startSlot, duration);
}

export function ProgramOturumListele(): $CancellablePromise<$models.ProgramOturumu[] | null> {
    return $Call.ByID(1860473599);
}

export function ProgramOturumSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(667300007, id);
}

export function SubeEkle(ad: string): $CancellablePromise<domain$0.Sube> {
    return $Call.ByID(2399803115, ad);
}

export function SubeListele(): $CancellablePromise<domain$0.Sube[] | null> {
    return $Call.ByID(2887128800);
}

export function SubeSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(1696262536, id);
}

export function ToplantiTuruEkle(ad: string): $CancellablePromise<domain$0.ToplantiTuru> {
    return $Call.ByID(752381417, ad);
}

export function ToplantiTuruListele(): $CancellablePromise<domain$0.ToplantiTuru[] | null> {
    return $Call.ByID(2034350802);
}

export function ToplantiTuruSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(3878888994, id);
}

export function ZoomEkle(ad: string, adres: string): $CancellablePromise<domain$0.Zoom> {
    return $Call.ByID(2856330457, ad, adres);
}

export function ZoomListele(): $CancellablePromise<domain$0.Zoom[] | null> {
    return $Call.ByID(2482967010);
}

export function ZoomSil(id: number): $CancellablePromise<void> {
    return $Call.ByID(682508370, id);
}
