// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    Ders,
    Hoca,
    Sube,
    ToplantiTuru,
    Zoom
} from "./models.js";
