// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Ders, bir branşı/kursu (ör. "Matematik") temsil eder.
 */
export interface Ders {
    "ID": number;
    "Ad": string;
}

/**
 * Hoca, bir öğretmen.
 */
export interface Hoca {
    "ID": number;
    "Ad": string;
}

/**
 * Sube, bir sınıf/şube (ör. "9-A").
 */
export interface Sube {
    "ID": number;
    "Ad": string;
}

/**
 * ToplantiTuru, programa konan bir oturumun ne tür olduğunu belirtir.
 * Her şey "ders" değil: hocalar bazen seminere/toplantıya da giriyor.
 * Örnekler: "Ders", "Seminer", "Veli Toplantısı".
 */
export interface ToplantiTuru {
    "ID": number;
    "Ad": string;
}

/**
 * Zoom, bir çevrimiçi ders adresi.
 */
export interface Zoom {
    "ID": number;

    /**
     * tanıtıcı etiket (ör. "Zoom Hesabı 1")
     */
    "Ad": string;

    /**
     * bağlantı (ör. https://zoom.us/j/...)
     */
    "Adres": string;
}
